language: php
php:
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4'
cache:
    directories:
        - $HOME/.composer/cache/files
install:
    - composer install
script:
    - mkdir -p build/logs
    - vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover build/logs/clover.xml
after_script:
    - travis_retry php vendor/bin/php-coveralls -v